### ISSUE TITLE
[BUG] the UI says "Undefined" when I create a new base inside a collection

### ISSUE THREAD

**Issue by AvikantSrivastava** [deta/deta#3]
<img width="581" alt="image" src="https://github.com/deta/deta/assets/41926176/7ab050f4-e087-4c21-a574-2e079afb4581">

collection slug: `https://deta.space/collections/c0njtefz3al`

**Comment by aavshr** [comment]
thanks @AvikantSrivastava for the report, sorry for getting back so late. Since we've shut down space now I'm closing this issue
